// Generates src/web/styles/tokens.css from the stored ChromaJev scheme so the
// application's colours always come from the scheme, never from hand-picked values.
import { readFileSync, writeFileSync } from 'node:fs';

const scheme = JSON.parse(readFileSync(new URL('../design/rain-and-wind-on-rathlin.json', import.meta.url), 'utf8'));
const kebab = (s) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
const block = (tokens) => Object.entries(tokens).map(([k, v]) => `  --c-${kebab(k)}: ${v};`).join('\n');

const css = `/*
 * Generated by scripts/generate-tokens.mjs from design/rain-and-wind-on-rathlin.json
 * (ChromaJev scheme "${scheme.name}"). Do not edit by hand.
 */
:root,
:root[data-theme='light'] {
  color-scheme: light;
${block(scheme.light)}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${block(scheme.dark)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${block(scheme.dark).replace(/^/gm, '  ')}
  }
}
`;
writeFileSync(new URL('../src/web/styles/tokens.css', import.meta.url), css);
console.log('tokens.css written');
